// Add to Person a createGreetingsForFriends method which will return an array of strings - each string in the array is a greeting generated by the createGreeting method. For example:
//
// > var alfie = new Person('Alfie');
// > var anushka = new Person('Anushka');
// > var henrique = new Person('Henrique');
// > alfie.addFriend(anushka);
// > alfie.addFriend(henrique);
// > alfie.createGreetingsForFriends();
// ["Yo Anushka! from Alfie.", "Yo Henrique! from Alfie."]
// Do this without using a loop but by using map instead.

class Person {
    constructor (name) {
        this.name = name;
        this.friends = [];
        this.greeting = [];
    }
    addFriend(friend) {
        this.friends.push(friend);
    }
    createGreeting(other) {
        this.greeting.push('Yo ' + other.name + '! from ' + this.name + '.')
    }
    createGreetingsForFriends() {

    }
}

var alfie = new Person('Alfie');
var anushka = new Person('Anushka');
var henrique = new Person('Henrique');

alfie.addFriend(henrique);
console.log(alfie)


// console.log(alfie.addFriend(anushka));
alfie.addFriend(henrique);
// alfie.createGreetingsForFriends();
