# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

ls = [1,2]
evenLs = []
while ls[-1] <= 4000000:
    ls.append(ls[-1] + ls[-2])

newLs = ls[0:-1]
for j in newLs:
    if j % 2 == 0:
        evenLs.append(j)

print(sum(evenLs))



# ls = [1, 2]
# for i in range(1, 50):
#     ls.append(ls[-1] + ls[-2])
#     if ls[-1] >= 4000000:
#         break
#
